// <auto-generated />
namespace StudentRecruiter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class seed11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seed11));
        
        string IMigrationMetadata.Id
        {
            get { return "201912291355164_seed11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
